import type { Metadata } from "next";
import {DM_Sans, Outfit } from "next/font/google";
import "./globals.css";
import App from "next/app";

const AppFont = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Video Course Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={AppFont.className}
      >
        {children}
      </body>
    </html>
  );
}
